### ISSUE TITLE
Different power source connection

### ISSUE THREAD

**Issue by tagooricho** [MECHALABS-LLC/circuitTest3#3]
How do I connect the components if I have an external power source, like a 9V battery?

**Comment by mykeTheArchAngel** [comment]
> How do I connect the components if I have an external power source, like a 9V battery?

The Arduino Pin 13 is connected to the base of the NPN transistor through a 220Ω resistor.
The collector of the transistor is connected to Terminal 1 of the DC motor.
The emitter of the transistor is connected to the ground (GND) of the Arduino.
Terminal 2 of the DC motor is connected to the positive terminal of the 9V battery.
The ground of the Arduino and the ground of the 9V battery should be connected together to ensure a common reference.
